# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Runs a set of commands using the runners shell
      - name: Print 1
        run: echo Pipe pregatit
        
      # Runs a set of commands using the runners shell
      - name:  Print 1
        run: echo Pasul 2 printat
        
  test:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:

        # Runs a set of commands using the runners shell
        - name: Test1 1
          run: echo Teste ostman

        # Runs a set of commands using the runners shell
        - name:  Test2 1
          run: echo Teste python
